Update cinebox_fe.yaml
- run ubuntu
- set nodeJS
- package newly install
- build
- make artifact

diff --git a/.github/workflows/cinebox_fe.yaml b/.github/workflows/cinebox_fe.yaml
--- a/.github/workflows/cinebox_fe.yaml
+++ b/.github/workflows/cinebox_fe.yaml
@@ -18,43 +18,52 @@ jobs:
           npm -v
           node -v
 
+      - name: set init package
+        run: |
+          rm -rf node_modules package-lock.json
+          npm install
+
       - name: Make .env file
         run: |
-          cd ./src/main/resources
           touch ./.env
-          echo "${{ secrets.AWSPROPERTIES }}" > ./application.properties
+          echo "${{ secrets.ENV }}" > ./.env
         shell: bash
 
-      - name: Build with Maven
+      - name: Verify .env file
+        run: cat ./.env
+  
+      - name: Build with npm
         run: |
-          cd $HOME/cinebox
-          npm run build
+          npm run build || { echo "Build failed!"; exit 1; }
+
+      - name: Verify build output
+        run: du -sh ./build
 
       - name: Check build folder
         run: ls ./build
 
       - uses: actions/upload-artifact@v4
         with:
-          name: app
-          path: ./target/*.jar
+          name: cinebox
+          path: ./build
 
-      - name: Configure AWS credentials 
-        run: |
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
-          aws configure set default.region ${{ secrets.REGION }}
-          aws configure set output json
+      # - name: Configure AWS credentials 
+      #   run: |
+      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+      #     aws configure set default.region ${{ secrets.REGION }}
+      #     aws configure set output json
           
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+      # - name: Set up QEMU
+      #   uses: docker/setup-qemu-action@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
 
-      - name: Build and push
-        run: |
-          aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECRID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com
-          docker buildx build --platform linux/amd64 -t ${{ secrets.ECRURL }}:${{ github.sha }} --push .
+      # - name: Build and push
+      #   run: |
+      #     aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECRID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com
+      #     docker buildx build --platform linux/amd64 -t ${{ secrets.ECRURL }}:${{ github.sha }} --push .
 
 
   # cd:
