Update cinebox_fe.yaml
CI=false npm run build < ESLint 에서 warning 도 오류로 간주하는 상태 변경

diff --git a/.github/workflows/cinebox_fe.yaml b/.github/workflows/cinebox_fe.yaml
--- a/.github/workflows/cinebox_fe.yaml
+++ b/.github/workflows/cinebox_fe.yaml
@@ -35,7 +35,7 @@ jobs:
   
       - name: Build with npm
         run: |
-          npm run build || { echo "Build failed!"; exit 1; }
+          CI=false npm run build || { echo "Build failed!"; exit 1; }
 
       - name: Verify build output
         run: du -sh ./build
